### ISSUE TITLE
斗鱼活动直播间界面不显示播放器

### ISSUE THREAD

**Issue by hao1196561270** [wuxin0011/huya-live#1]
![image](https://user-images.githubusercontent.com/129362575/230862542-deeef9e0-8a47-4728-a080-a58f0fbafd74.png)
如图，有声音无画面😂

**Comment by wuxin0011** [comment]
问题已修复，感谢提bug！

**Comment by hao1196561270** [comment]
> 问题已修复，感谢提bug！

感谢

**Comment by hao1196561270** [comment]
> 问题已修复，感谢提bug！

你好请问一下默认是小窗播放怎么设置为默认是正常窗口播放如图
![image](https://user-images.githubusercontent.com/129362575/231945388-c2c7efeb-3096-4dc8-bc61-164009705050.png)
![image](https://user-images.githubusercontent.com/129362575/231945415-40f40770-cb85-4e62-a57c-70c514d63dd8.png)

**Comment by wuxin0011** [comment]
关于这个问题，在一些小窗口直播会出现这个问题，可能屏蔽大量页面内容特别是底部内容，斗鱼检测到误以为我下滑，将直播视频 小窗口播放了，不过我设置延迟检测，如果出现了小窗口，将自动点击关闭；但是由于网络原因，有时候超过了检测时间才出现检测；导致小窗口没有关闭，只能通过手动关闭。
这个问题我试试看看能不能用 使用 轮询检测 解决。

**Comment by wuxin0011** [comment]
如果设置延迟时间过大，也会造成体验不过，过短有时候无法检测到

**Comment by wuxin0011** [comment]
![image](https://user-images.githubusercontent.com/65836396/231994471-8da32a42-00c6-4353-a04c-21d688cdae87.png)

**Comment by wuxin0011** [comment]
这个问题我在当前脚本存在问题写出来了

**Comment by wuxin0011** [comment]
我试试少屏蔽一些内容看看能不能解决

**Comment by wuxin0011** [comment]
更新了，能够自动关闭小窗口了，不过无法屏蔽

**Comment by hao1196561270** [comment]
> 

好的 感谢

**Comment by hao1196561270** [comment]
![image](https://user-images.githubusercontent.com/129362575/232981150-b10f18a2-8851-4c71-934b-64270a819997.png)
斗鱼直播quan全屏时右下角有一个回到顶部的按钮

**Comment by hao1196561270** [comment]
> 
希望修复一下

**Comment by wuxin0011** [comment]
已修复

**Comment by hao1196561270** [comment]
你好 想问一下斗鱼可以加一个送礼物栏的开关吗？ 有送礼物的需求 开了插件没有办法送礼物  QAQ  谢谢

**Comment by wuxin0011** [comment]
已经把这个添加上去了，操作面板可以通过点击直播平台的logo显示了

**Comment by hao1196561270** [comment]
> 已经把这个添加上去了，操作面板可以通过点击直播平台的logo显示了

我刚刚试了一下斗鱼的背包无法打开 如图显示
![背包](https://user-images.githubusercontent.com/129362575/234535659-31215275-ca62-4f35-ab7f-53fa67154ed9.gif)

**Comment by hao1196561270** [comment]
![image](https://user-images.githubusercontent.com/129362575/234536630-4ac86c29-1beb-4d04-9565-478a3a7ae65f.png)
这三个也是如图显示闪一下界面就消失了😳

**Comment by wuxin0011** [comment]
我看下

**Comment by wuxin0011** [comment]
已经修复了，是之前小窗口问题导致的，不过还是采取了一定延迟，需要有一定延迟才能正常点击。
另外我这边看不了充值窗口，网速有点慢，不知道这个还有没有问题，先这样吧

**Comment by hao1196561270** [comment]
请问一下抖音网页版的默认全屏模式怎么手动设置不全屏

**Comment by wuxin0011** [comment]
这个暂时没弄，简单倒是很简单  但是不想加 ，原来是自己用着玩的🤣

**Comment by wuxin0011** [comment]
没想到还真有人在乎这个🤣

**Comment by hao1196561270** [comment]
> 没想到还真有人在乎这个🤣

![image](https://github.com/wuxin0011/huya-live/assets/129362575/cb20494d-768b-4f36-bc53-43dfeb6189d1)
![image](https://github.com/wuxin0011/huya-live/assets/129362575/a1b46da4-b08f-475a-b17a-46ba82552893)
那个现在我没问题了  现在斗鱼的礼物栏是错位的 希望fix一下

**Comment by hao1196561270** [comment]
> > 没想到还真有人在乎这个🤣
> 
> ![image](https://user-images.githubusercontent.com/129362575/266543893-cb20494d-768b-4f36-bc53-43dfeb6189d1.png) ![image](https://user-images.githubusercontent.com/129362575/266543989-a1b46da4-b08f-475a-b17a-46ba82552893.png) 那个现在我没问题了 现在斗鱼的礼物栏是错位的 希望fix一下

不修复也能用 不耽误现在

**Comment by wuxin0011** [comment]
新增了虎牙斗鱼黑夜主题，可以试下，更新到最新版本就可以体验了，默认是自动开启的
