### ISSUE TITLE
B站动态页面的暗黑模式没有覆盖背景

### ISSUE THREAD

**Issue by Liekkipuu** [wuxin0011/huya-live#4]
顺便问问能不能靠脚本让抖音直播页面,能在后台黑听的时候,不会因为没有操作而进入节能暂停的状态

**Comment by wuxin0011** [comment]
截图看看那啥意思 ？

**Comment by wuxin0011** [comment]
> 顺便问问能不能靠脚本让抖音直播页面,能在后台黑听的时候,不会因为没有操作而进入节能暂停的状态

暂时没弄这个，应该可以加进去，下次吧

**Comment by Liekkipuu** [comment]
> 截图看看那啥意思 ？

![动态首页-哔哩哔哩 and 6 more pages - Personal - Microsoft​ Edge 12_15_2023 6_08_04 PM](https://github.com/wuxin0011/tampermonkey-script/assets/143843452/8620c335-a6e6-44ec-8419-c25e8e1f8cb1)

**Comment by wuxin0011** [comment]
你说这个页面啊，我当初弄的时候当时是全黑，但是感觉不是很好，后面就去掉了，感觉不覆盖还好看点不是吗
