### ISSUE TITLE
B站的控制按钮找不到.....

### ISSUE THREAD

**Issue by ToBEaNewbility** [wuxin0011/huya-live#6]

**Comment by ToBEaNewbility** [comment]
![image](https://github.com/wuxin0011/tampermonkey-script/assets/104293833/dded9471-d52d-460e-85f5-7523801df10f)

**Comment by ToBEaNewbility** [comment]
直播间也是，有效果，但是找不到按钮入口

**Comment by wuxin0011** [comment]
> 直播间也是，有效果，但是找不到按钮入口

按下快捷键 `Ctrl+Alt+J`

之前有人反馈不需要就移除了，现在保持快捷键方式打开，下次更新放到插件控制哪里

**Comment by ToBEaNewbility** [comment]
ok，tk！
