### ISSUE TITLE
哔哩哔哩直播界面无法呼出

### ISSUE THREAD

**Issue by 360faker** [wuxin0011/huya-live#7]
logo和快捷键都不行，视频界面没问题

**Comment by wuxin0011** [comment]
> logo和快捷键都不行，视频界面没问题

B站直播界面很好，不需要优化，没什么广告就移除了

**Comment by wuxin0011** [comment]
另外 B站 Logo 唤起也移除了，有人反映需要直接点击logo回到首页

**Comment by 360faker** [comment]
> 另外 B站 Logo 唤起也移除了，有人反映需要直接点击logo回到首页

虽然优化直播页面其他大佬已经做的很好了，但目前还没有自定义背景以及自动网页全屏的脚本，那个自动最高画质的也有一些问题，还是希望可以加回来

**Comment by wuxin0011** [comment]
好的，我看看
